spring:
  datasource:
    username: container_therapy
    password: container_therapy
    url: jdbc:mysql://localhost:3306/container_therapy
    
  jpa:
     hibernate:
        ddl-auto: update
     show-sql: true
     defer-datasource-initialization: true
     
  sql:
     init:
        mode: always